FROM ubuntu:latest

WORKDIR /app

# Install missing system tools
RUN apt-get update && apt-get install -y findutils procps util-linux unzip curl

# Install AWS CLI v2
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install

# Copy your script
COPY Automation/functions/monitor.sh .
RUN chmod +x monitor.sh

# Create log directory
RUN mkdir -p /app/log_monitor

CMD ["./monitor.sh"]
