name: Build and Test Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Set up Docker Buildx (required for Docker builds in Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 - Build Docker image
      - name: Build Docker image
        run: docker build -t system-health:v1 -f Dockerfile .


      # Step 4 - Run container to verify
      - name: Run container
        run: docker run system-health:v1
