name: Build and Test Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 - Set up Docker Buildx (required for Docker builds in Actions)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 - Build Docker image
      - name: Build Docker image
        working-directory: ${{ github.workspace }}
        run: docker build -t system-health:${{ github.run_number }} -f Dockerfile .

      - name: Run container and save output
        run: docker run system-health:${{ github.run_number }} > output.log

      - name: Upload result log
        uses: actions/upload-artifact@v4
        with:
          name: container-output
          path: output.log

