name: Monitor Script Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'Automation/functions/monitor.sh'
      - 'Automation/functions/log_monitor/**'

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Validate AWS identity
        run: aws sts get-caller-identity

      - name: Run monitor script
        run: |
          cd Automation/functions
          chmod +x monitor.sh
          ./monitor.sh

      - name: Upload log artifact
        uses: actions/upload-artifact@v4
        with:
          name: monitor-logs
          path: Automation/functions/log_monitor/*.log
